# Generated by Django 3.2.6 on 2021-09-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Telephone', models.CharField(max_length=12)),
                ('Subject', models.TextField()),
                ('Message', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadsBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=30)),
                ('Book_Name', models.CharField(max_length=200)),
                ('Author_Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('ReleaseDate', models.DateField()),
                ('Selling_price', models.FloatField()),
                ('Label', models.CharField(choices=[('o', 'Old'), ('N', 'New')], max_length=2)),
                ('Publication', models.CharField(max_length=200)),
                ('Types_of_Book', models.CharField(choices=[('Action and Adventure', 'Action and Adventure'), ('Classics', 'Classics'), ('Comic Book or Graphic Novel', 'Comic Book or Graphic Novel.'), ('Detective and Mystery', 'Detective and Mystery'), ('Fantasy', 'Fantasy'), (' Historical Fiction', ' Historical Fiction'), ('Horror', ' Horror'), ('Literary Fiction', 'Literary Fiction'), ('School', 'School'), ('+2', '+2'), ('+2', '+2'), ('Bachelor', 'Bachelor'), ('Bachelor', 'Bachelor'), ('Master  and degree', 'Master  and degree'), ('Other', 'Others')], max_length=100)),
                ('Quantity', models.PositiveBigIntegerField(default=1)),
                ('Image', models.ImageField(upload_to='book_images/')),
                ('Seller_phoneno', models.PositiveBigIntegerField()),
                ('Seller_address', models.CharField(max_length=200)),
            ],
        ),
    ]
