# Generated by Django 3.2.6 on 2021-09-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsbook',
            name='Label',
            field=models.CharField(choices=[('Old', 'Old'), ('New', 'New')], default='New', max_length=3),
        ),
        migrations.AlterField(
            model_name='uploadsbook',
            name='Publication',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='uploadsbook',
            name='Types_of_Book',
            field=models.CharField(choices=[('Action and Adventure', 'Action and Adventure'), ('Classics', 'Classics'), ('Comic Book or Graphic Novel', 'Comic Book or Graphic Novel.'), ('Detective and Mystery', 'Detective and Mystery'), ('Fantasy', 'Fantasy'), (' Historical Fiction', ' Historical Fiction'), ('Horror', ' Horror'), ('Literary Fiction', 'Literary Fiction'), ('School', 'School'), ('+2', '+2'), ('+2', '+2'), ('Bachelor', 'Bachelor'), ('Bachelor', 'Bachelor'), ('Master  and degree', 'Master  and degree'), ('Other', 'Others')], default='Action and Adventure', max_length=300),
        ),
    ]
