# Generated by Django 3.2.6 on 2021-08-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_uploadsbook_releasedates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Telephone', models.CharField(max_length=12)),
                ('Subject', models.TextField()),
                ('Message', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
