# Generated by Django 3.2.6 on 2021-09-02 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadsbook',
            old_name='Lable',
            new_name='Label',
        ),
        migrations.RenameField(
            model_name='uploadsbook',
            old_name='ReleaseDates',
            new_name='ReleaseDate',
        ),
        migrations.RemoveField(
            model_name='uploadsbook',
            name='Discount_price',
        ),
        migrations.AddField(
            model_name='uploadsbook',
            name='isbn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
