# Generated by Django 3.2.6 on 2021-09-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210902_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsbook',
            name='isbn',
            field=models.CharField(max_length=30),
        ),
    ]
