# Generated by Django 3.2.6 on 2021-09-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_uploadsbook_isbn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadsBook',
        ),
    ]
