# Generated by Django 3.2.6 on 2021-09-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_personal_information_username'),
        ('books', '0007_uploadsbook'),
    ]

    operations = [
    ]
