# Generated by Django 3.2.6 on 2021-09-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_merge_20210902_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_information',
            name='username',
        ),
    ]
