# Generated by Django 3.2.6 on 2021-09-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_personal_information_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='personal_information',
        ),
        migrations.AddField(
            model_name='uploadsbook',
            name='Seller_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uploadsbook',
            name='Seller_phoneno',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
